name: Build Desktop Installers
on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

jobs:
  build-release:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Install web deps
        working-directory: webapp
        run: |
          npm ci
          npm run build

      - name: Build bridge (PyInstaller)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller -r p2p_bridge/requirements.txt
          pyinstaller -F p2p_bridge/bridge.py -n bridge
        shell: bash

      - name: Prepare desktop payload
        run: |
          mkdir -p desktop/dist desktop/bin
          # copiar UI
          cp -r webapp/dist/* desktop/dist/
          # copiar binario del bridge
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp dist/bridge.exe desktop/bin/bridge.exe
          else
            cp dist/bridge desktop/bin/bridge
            chmod +x desktop/bin/bridge
          fi

      - name: Install electron deps
        working-directory: desktop
        run: npm ci

      - name: Build installers
        working-directory: desktop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: desktop/release/**
