name: Build Desktop Installers
on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:
    inputs:
      version:
        description: "Version (ej. v1.2.3). Si lo dejas vacío y no hay tag, fallará."
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build-release:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: { os: [ubuntu-latest, windows-latest, macos-latest] }

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      # Compila la PWA si existe en webapp/
      - name: Build webapp (si existe)
        if: ${{ hashFiles('webapp/package.json') != '' }}
        working-directory: webapp
        run: |
          npm ci || npm install
          npm run build

      # Empaqueta el bridge si existe (PyInstaller)
      - name: Build bridge (si existe)
        if: ${{ hashFiles('p2p_bridge/bridge.py') != '' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller -r p2p_bridge/requirements.txt
          pyinstaller -F p2p_bridge/bridge.py -n bridge
        shell: bash

      - name: Install deps (Electron)
        working-directory: desktop
        run: npm ci || npm install

      - name: Build installers
        working-directory: desktop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.version }}" ]; then
            npx electron-builder -c.extraMetadata.version=${{ github.event.inputs.version }}
          else
            npx electron-builder
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}
          name: "Release ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}"
          files: |
            desktop/release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
